services:
  - type: web
    name: grocery2go-frontend
    runtime: static
    plan: free
    rootDir: frontendcode
    buildCommand: (npm ci || npm install) && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: grocery2go-api
    runtime: docker
    plan: free
    rootDir: backendcode
    healthCheckPath: /health
